AWSTemplateFormatVersion: 2010-09-09
Description: "WS SSM StackSet"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - 
        Label: 
          default: 'Automation details'
        Parameters:
          - IsDelegatedAdministrator
          - DelegatedAdminAccountId
          - ManagementAccountId
      - 
        Label:
          default: 'Targets'
        Parameters:
          - DeploymentTargets
          - TargetOUs
          - TargetKey
          - TargetValues
      - 
        Label:
          default: 'Cloud One Workload Security'
        Parameters:
          - dsActivationUrl
          - dsManagerUrl
          - dsTenantId
          - dsToken
Parameters:
  IsDelegatedAdministrator:
    Type: String
    AllowedValues:
    - 'true'
    - 'false'
    Description: Specify if this solution is being deployed in a delegated adminstrator account. With this option you no longer need to be logged into the AWS Organizations management account to administer software package distribution.
  DeploymentTargets:
    Description: Specify AWS Organizational Unit IDs within AWS Organization whose accounts have the target instances (ou-name) for distribution. (Account IDs are only allowed when updating)
    Type: CommaDelimitedList
    Default: 'ou-8rkd-yyf0tyki'
  TargetKey:
    Type: String
    Description: Specify which instances have to be targeted for this solution. Allowed values - ParameterValues, ResourceGroup or begin with tag:, AWS::EC2::Instance, InstanceIds (default), instanceids. Refer https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_Target.html for more details.
    Default: 'InstanceIds'
  TargetValues:
    Type: String
    Description: Specify the values of the target keys specified above. Default is *, which targets all instances. Refer https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_Target.html for more details.
    Default: '*'
  ManagementAccountId:
    Description: (Required) AWS Organization's Management account ID.
    Type: String
    Default: '024368254241'
  DelegatedAdminAccountId:
    Description: (Optional) Delegated administrator account ID.
    Type: String
    Default: ''
  dsActivationUrl:
    Type: String
    Description: "Cloud One Workload Security Activation URL."
    NoEcho: true
    Default: 'dsm://agents.deepsecurity.trendmicro.com:443/'
  dsManagerUrl:
    Type: String
    Description: "Cloud One Workload Security Manager URL."
    NoEcho: true
    Default: 'https://app.deepsecurity.trendmicro.com:443'
  dsTenantId:
    Type: String
    Description: "Cloud One Workload Security Tenant ID."
    NoEcho: true
    Default: 'BF79CB10-0B4C-CCFA-A10F-9E2E4FCEFD03'
  dsToken:
    Type: String
    Description: "Cloud One Workload Security Token ID."
    NoEcho: true
    Default: '57573BC0-3D28-C25D-DDC9-66742C980F07'
  
Conditions:
  IsDelegatedAdministrator: 
    !Equals [!Ref IsDelegatedAdministrator,'true']
  IsGovCloud: 
    !Or [!Equals [!Ref AWS::Region, us-gov-west-1], !Equals [!Ref AWS::Region, us-gov-east-1]]
Resources:
  StackSetExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !GetAtt StackSetAdministrationRole.Arn
            Action: sts:AssumeRole
      Policies:
        - PolicyName: allow-deploy-ssm-dist
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: cloudformation:*
                Resource: '*'
              - Effect: Allow
                Action:
                  - iam:CreateRole
                  - iam:AttachRolePolicy
                  - iam:PutRolePolicy
                  - iam:PassRole
                  - iam:DetachRolePolicy
                  - iam:DeleteRolePolicy
                  - iam:GetRole
                  - iam:DeleteRole
                  - iam:GetRolePolicy
                Resource: '*'
              - Effect: Allow
                Action:
                  - kms:CreateGrant
                  - kms:Decrypt
                  - kms:DescribeKey
                  - kms:Encrypt
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'ssm:PutParameters'
                  - 'ssm:DescribeParameters'
                  - 'ssm:DeleteParameters'
                  - 'ssm:GetParameter'
                  - 'ssm:GetParameters'
                  - 'ssm:CreateAssociation'
                  - 'ssm:DescribeAssociation'
                  - 'ssm:DeleteAssociation'
                  - 'ssm:ListTagsForResource'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'resource-groups:ListGroupResources'
                  - 'tag:GetResources'
                  - 'ec2:DescribeInstances'
                  - 'ec2:DescribeTags'
                  - 'ec2messages:GetEndpoint'
                  - 'ec2messages:FailMessage'
                  - 'ec2messages:AcknowledgeMessage'
                  - 'ec2messages:SendReply'
                  - 'ec2messages:GetMessages'
                  - 'organizations:ListAccountsForParent'
                  - 'organizations:ListOrganizationalUnitsForParent'
                Resource: '*'

  StackSetAdministrationRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole

  SSMStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties: 
      AutoDeployment:
          Enabled: true
          RetainStacksOnAccountRemoval: false
      CallAs: !If [IsDelegatedAdministrator,DELEGATED_ADMIN,SELF]
      Capabilities:
          - CAPABILITY_AUTO_EXPAND
          - CAPABILITY_IAM
          - CAPABILITY_NAMED_IAM
      Description: SSM Stackset for C1WS
      Parameters: 
        - 
          ParameterKey: dsActivationUrl
          ParameterValue: !Ref dsActivationUrl
        - 
          ParameterKey: dsManagerUrl
          ParameterValue: !Ref dsManagerUrl
        - 
          ParameterKey: dsTenantId
          ParameterValue: !Ref dsTenantId
        - 
          ParameterKey: dsToken
          ParameterValue: !Ref dsToken
        - 
          ParameterKey: TargetKey
          ParameterValue: !Ref TargetKey
        - 
          ParameterKey: TargetValues
          ParameterValue: !Ref TargetValues
      PermissionModel: SERVICE_MANAGED
      StackInstancesGroup:
          - Regions:
            - us-east-1
            - us-east-2
            DeploymentTargets:
              OrganizationalUnitIds: !Ref DeploymentTargets
      StackSetName: C1WS-SSM-StackSet
      TemplateBody: |
        Parameters:
          dsActivationUrl:
            Type: String
            Description: "Cloud One Workload Security Activation URL."
            NoEcho: true
          dsManagerUrl:
            Type: String
            Description: "Cloud One Workload Security Manager URL."
            NoEcho: true
          dsTenantId:
            Type: String
            Description: "Cloud One Workload Security Tenant ID."
            NoEcho: true
          dsToken:
            Type: String
            Description: "Cloud One Workload Security Token ID."
            NoEcho: true
          TargetKey:
            Type: String
            Description: Specify which instances have to be targeted for this solution. Allowed values - ParameterValues, ResourceGroup or begin with tag:, AWS::EC2::Instance, InstanceIds (default), instanceids. Refer https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_Target.html for more details.
            Default: 'InstanceIds'
          TargetValues:
            Type: String
            Description: Specify the values of the target keys specified above. Default is *, which targets all instances. Refer https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_Target.html for more details.
            Default: '*'
        Resources:
          DSActivationUrlParam:
            Type: "AWS::SSM::Parameter"
            Properties:
              Name: "dsActivationUrl"
              Type: "String"
              Value: !Ref dsActivationUrl
              Description: "Cloud One Workload Security Activation URL"
              Tags:
                Key: CloudOne
                Value: WS-SSM
          DSManagerUrlParam:
            Type: "AWS::SSM::Parameter"
            Properties:
              Name: "dsManagerUrl"
              Type: "String"
              Value: !Ref dsManagerUrl
              Description: "Cloud One Workload Security Manager URL"
              Tags:
                Key: CloudOne
                Value: WS-SSM
          DSTenantIdParam:
            Type: "AWS::SSM::Parameter"
            Properties:
              Name: "dsTenantId"
              Type: "String"
              Value: !Ref dsTenantId
              Description: "Cloud One Workload Security Tenant ID"
              Tags:
                Key: CloudOne
                Value: WS-SSM
          DSTokenParam:
            Type: "AWS::SSM::Parameter"
            Properties:
              Name: "dsToken"
              Type: "String"
              Value: !Ref dsToken
              Description: "Cloud One Workload Security Token ID"
              Tags:
                Key: CloudOne
                Value: WS-SSM
          C1WSDistributorPackage:
            Type: AWS::SSM::Association
            Properties:
              AssociationName: TrendCloudOneWorkloadSecurityAssociation
              Name: AWS-ConfigureAWSPackage
              Parameters: 
                action:
                  - Install
                installationType:
                  - In-place update
                name:
                  - TrendMicro-CloudOne-WorkloadSecurity
              Targets: 
                - Key: !Ref TargetKey
                  Values:
                  - !Ref TargetValues

